spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.josdem.io/
auth:
  username: "josdem"
  password: "12345678"
app:
  token: "71705378-b5ad-4e4d-a043-2d1278d75554"
inventory:
  products:
    - sku: "100"
      name: "Nike Air Max 2023"
      price: 210
    - sku: "101"
      name: "Stan Smith"
      price: 110
swagger:
  server: "http://localhost:8080"
server:
  port: 8085


